### ISSUE TITLE
Support per-command help output

### ISSUE THREAD

**Issue by aperezdc** [aperezdc/virtualz#1]
TL;DR the following should work:

- [ ] `vz help <command>`
- [ ] `vz <command> -h|--help`

**Comment by ogarcia** [comment]
+1

**Comment by mkos** [comment]
It would enable changing how virtualenvs are activated from using 'activate' subcommand to `vz <venv_name>` as well. What do you think?

**Comment by aperezdc** [comment]
@mkos I like the idea, so I have created an issue (#2) to track it. Thanks for the suggestion!
