### ISSUE TITLE
realpath not found in path.

### ISSUE THREAD

**Issue by jimmyharris** [aperezdc/virtualz#3]
When loading your script with zplug I get the following error:

```
/home/<username>/.config/zplug/repos/aperezdc/virtualz/virtualz.plugin.zsh:11: command not found: realpath
```

I am using Ubuntu 14.04 and zsh 5.0.2.

Some research on stack exchange brought me to [this question](http://unix.stackexchange.com/questions/76505/portable-way-to-get-scripts-absolute-path) which stated that zsh didn't have a `realpath` builtin but had some shell expansion flags for getting the `realpath` of a script. This syntax looks something like this:
```zsh
my_script_path=${0:A}
```

I am not sure if this would follow the symlinks or not, but I am not sure that that is relevant to this case.
This means that one solution would be replace line 11 of `virtualz.plugin.zsh` with:

```zsh
typeset -gr _virtualz_dir=${0:a:h}
```
 to get the directory virtualz was installed into.

**Comment by aperezdc** [comment]
This is a great suggestion! Thanks a lot for pointing out this Zsh feature, it's really handy :+1:

**Comment by jimmyharris** [comment]
Are you sure the ${0:A} method will give you the path you wanted? For me it gives the full path to the existing file.

**Comment by aperezdc** [comment]
@jimmyharris, I saw your PR... and you're right, I should have spent a little bit of time testing before my previous commit. I've merged your PR, which makes everything work again. Thanks!
